services:
    sio_test:
        user: app
        build:
            context: .
            args:
                USER_ID: ${USER_ID:-1000}
        ports:
            - "8337:8337"
        volumes:
            - .:/app:rw
        environment:
            - APP_ENV=dev

    test-task-postgres:
        image: postgres:17.4-alpine
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        volumes:
            - test-task-postgres:/var/lib/postgresql/data
        ports:
            - "54321:5432"

volumes:
    test-task-postgres:
