### Calculate Price
POST http://127.0.0.1:8337/calculate-price
Accept: application/json
Content-Type: application/json

{
  "productId": "a022fe44-3ba4-4b31-99aa-9f965e1ad15d",
  "taxNumber": "DE123456789",
  "couponCode": "D15"
}

### Execute Purchase
POST http://127.0.0.1:8337/purchase
Accept: application/json
Content-Type: application/json

{
  "productId": "a022fe44-3ba4-4b31-99aa-9f965e1ad15d",
  "taxNumber": "IT12345678900",
  "couponCode": "D15",
  "paymentMethod": "paypal"
}
